//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMCEmpleados.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Cryptography;
    using System.Text;

    public partial class Usuario
    {
        public string usu_user_name { get; set; }
        public string usu_user_domain { get; set; }
        public string usu_user_email { get; set; }
        public string usu_password { get; set; }
        public string usu_nom_ape { get; set; }
        public System.DateTime usu_fecha_alta { get; set; }
        public Nullable<System.DateTime> usu_ult_login { get; set; }
        public Nullable<System.DateTime> usu_ult_logout { get; set; }

        internal static Usuario LogIn(Usuario usuario)
        {
            if (usuario != null && !string.IsNullOrWhiteSpace(usuario.usu_user_name) && 
                !string.IsNullOrWhiteSpace(usuario.usu_password) && !string.IsNullOrWhiteSpace(usuario.usu_user_email))
            {
                using (UsrDBEntities db = new UsrDBEntities())
                {
                    usuario.usu_password = Encryption(usuario.usu_password);
                    Usuario user = null;
                    IQueryable<Usuario> users = db.Usuarios.AsQueryable();
                    if (users != null && users.Count() > 0)
                        users = users.Where(x => x.usu_user_name.Equals(usuario.usu_user_name) &&
                                                x.usu_password.Equals(usuario.usu_password) &&
                                                x.usu_user_email.Equals(usuario.usu_user_email));

                    if (users != null && users.Count() > 0)
                        user = users.First();

                    if (user != null)
                    {
                        user.usu_ult_login = DateTime.Now;
                        user.usu_ult_logout = null;
                        db.SaveChanges();
                        return user;
                    }
                    else
                        return null;
                }
            }
            else
                return null;
        }

        internal static bool IsUserLog(string usuario, string email, string contraseña)
        {
            if (!string.IsNullOrWhiteSpace(usuario) && !string.IsNullOrWhiteSpace(contraseña))
            {
                using (UsrDBEntities db = new UsrDBEntities())
                {
                    Usuario user = null;
                    IQueryable<Usuario> users = db.Usuarios.AsQueryable();
                    if (users != null && users.Count() > 0)
                        user = users.Where(x => x.usu_user_name.Equals(usuario) &&
                                                x.usu_user_email.Equals(email) &&
                                                x.usu_password.Equals(contraseña)).First();

                    if (user != null && !string.IsNullOrEmpty(user.usu_user_name))
                        return true;
                    else
                        return false;
                }
            }
            else
                return false;
        }

        internal static Usuario LogOut(Usuario usuario)
        {
            if (usuario != null && !string.IsNullOrWhiteSpace(usuario.usu_user_name) && 
                !string.IsNullOrWhiteSpace(usuario.usu_password) && !string.IsNullOrWhiteSpace(usuario.usu_user_email))
            {
                using (UsrDBEntities db = new UsrDBEntities())
                {
                    Usuario user = null;
                    IQueryable<Usuario> users = db.Usuarios.AsQueryable();
                    if (users != null && users.Count() > 0)
                        user = users.Where(x => x.usu_user_name.Equals(usuario.usu_user_name) &&
                                                x.usu_password.Equals(usuario.usu_password) &&
                                                x.usu_user_email.Equals(usuario.usu_user_email)).First();

                    if (user != null)
                    {
                        user.usu_ult_logout = DateTime.Now;
                        db.SaveChanges();
                        return user;
                    }
                    else
                        return null;
                }
            }
            else
                return null;
        }

        private static string Encryption(String password)
        {
            MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();
            byte[] encrypt;
            UTF8Encoding encode = new UTF8Encoding();
            //encrypt the given password string into Encrypted data  
            encrypt = md5.ComputeHash(encode.GetBytes(password));
            StringBuilder encryptdata = new StringBuilder();
            //Create a new string by using the encrypted data  
            for (int i = 0; i < encrypt.Length; i++)
                encryptdata.Append(encrypt[i].ToString());

            return encryptdata.ToString();
        }
    }
}
